### PR TITLE
Update dependencies & small fix

### PR DESCRIPTION
**Pull request by nandolawson**
This project is no longer buildable because it uses a yanked version of cargo_toml. Accordingly, a simple fix is ​​to get the latest version of this dependency and all other dependencies.

Furthermore, a minimal fix is ​​included in the code.

### CODE REVIEW

**Comment by nandolawson** [comment]
Btw, it would be useful to enable Dependibot so that such problems do not occur in the future. In my opinion, an extremely good feature here on GitHub.

**Comment by nandolawson** [comment]
Is the project still being maintained?

**Comment by GeorgeLS** [comment]
> Is the project still being maintained?

@nandolawson 
Yes it is. However, I didn't have the time to review and merge due to work/travels.
Thank you for you work and for using the project!
I will review asap and come back yo you

**Comment by nandolawson** [comment]
No problem. I also used clippy to tweak the code a bit. The code should still work like it did before, but it is a bit cleaner now.

**Review by GeorgeLS — APPROVED** [review]

**Comment by GeorgeLS** [comment]
@nandolawson Thanks for your contribution!

**Comment by nandolawson** [comment]
Actually, I should thank you for this really useful software. After all, I only contributed a few small things. But you're welcome anyway.

**Pull request merged**
